
# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

amogh_dbt_practice:
  outputs:
    dev:
      type: snowflake
      account :
      warehouse :
      threads: 1
      user:
      password:
      role:
      database:
      schema:
      client_session_keep_alive: False
    prod:
